module.exports = {
    SET_LAST_PLAYING_COMMAND: 'SET_LAST_PLAYING_COMMAND',
    SET_SUBTITLES_LANG: 'SET_SUBTITLES_LANG',
    SET_AUDIO_LANG: 'SET_AUDIO_LANG',
    SAVE_TRANSCRIPT_ALTERNATIVES: 'SET_TRANSCRIPT_ALTERNATIVES'
}